# Generated by Django 5.2.1 on 2025-05-20 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=10)),
                ('database_status', models.TextField()),
                ('cache_status', models.TextField()),
                ('response_time_ms', models.FloatField()),
            ],
        ),
    ]
